export const ADD_TO_BOOKCART = 'ADD_TO_BOOKCART';
export const ADD_ARRAY_TO_BOOKCART = 'ADD_ARRAY_TO_BOOKCART';
export const DELETE_FROM_BOOKCART = 'DELETE_FROM_BOOKCART';
export const UPDATE_BOOK_IN_BOOKCART = 'UPDATE_BOOK_IN_BOOKCART'